name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kod yuklab olish
        uses: actions/checkout@v4

      - name: AWS EC2 ga deploy qilish
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/networking
            git pull origin main
            npm ci
            npm run build
            pm2 restart networking || pm2 start npm --name "networking" -- start